name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib
  - git
  - git-lfs
  - hvplot
  - holoviews
  - netCDF4
  - numpy
  - pandas
  - pip
  - rpy2
  - scipy
  - xarray
  - zarr
  - r-base=3.6
  - r-triebeard
  - r-stringi
  - r-curl
  - r-urltools
  - r-httpcode
  - r-rplyr
  - r-stringr
  - r-pkgconfig
  - r-rappdirs
  - r-crul
  - r-xml2
  - r-oai
  - r-tibble
  - r-hoardr
  - r-png
