name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib
  - git
  - git-lfs
  - hvplot
  - holoviews
  - netCDF4
  - numpy
  - pandas
  - pip
  - rpy2
  - scipy
  - xarray
  - zarr
